function A_m = Am_tmp(l1,l2,l3,m,m3,q1_m,q2_m,q3_m)
%AM_TMP
%    A_M = AM_TMP(L1,L2,L3,M,M3,Q1_M,Q2_M,Q3_M)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    06-Oct-2020 18:54:55

t2 = abs(l1);
t3 = abs(l2);
t4 = abs(l3);
t5 = conj(l2);
t6 = conj(q1_m);
t7 = conj(q2_m);
t8 = conj(q3_m);
t9 = cos(q1_m);
t10 = sin(q1_m);
t18 = 1.0./l2;
t19 = 1.0./l3;
t11 = cos(t7);
t12 = cos(t8);
t13 = sin(t7);
t14 = sin(t8);
t15 = t2.^2;
t16 = t3.^2;
t17 = t4.^2;
t20 = -t6;
t21 = -t8;
t22 = q1_m+t20;
t24 = t12.*t17;
t25 = l3.*t5.*t11.*2.0;
t26 = t14.*t17;
t27 = l3.*t5.*t13.*2.0;
t23 = cos(t22);
t28 = t26+t27;
t29 = t24+t25;
A_m = reshape([-m.*((l1.*t9.*t11.*t16.*t18)./2.0+(l1.*t10.*t13.*t16.*t18)./2.0)-m3.*((l1.*t9.*t19.*t29)./2.0+(l1.*t10.*t19.*t28)./2.0)+(m.*(t15.*t23-l1.*t5.*cos(q1_m-t7).*2.0))./4.0,(m.*t15.*t23)./4.0,l1.*m3.*t17.*t19.*cos(q1_m+t21).*(-1.0./2.0),m.*((t11.*t16.*cos(q2_m))./4.0+(t13.*t16.*sin(q2_m))./4.0),0.0,0.0,-m3.*((t29.*cos(q3_m))./4.0+(t28.*sin(q3_m))./4.0),0.0,m3.*t17.*cos(q3_m+t21).*(-1.0./4.0)],[3,3]);
